network:
  hidden_dim: 128
  dropout: 0.33
  num_layers: 6
train:
  lr: 0.0001
  epochs: 500
  random_seed: 2137
  lr_patience: 10 # use on test data
  weight_decay: 0
  early_stopping: 200
  batch_size: 64


#  optimum hyperparameters