network:
  hidden_dim: 256
  dropout: 0.5
  lr: 0.01
train:
  lr: 0.01
  epochs: 1000
  random_seed: 666
  lr_patience: 100 # use on test data
  weight_decay: 0.000
  early_stopping: 200
  batch_size: 128

#  optimum hyperparameters